### ISSUE TITLE
Blocker: app is crashing

### ISSUE THREAD

**Issue by shebin-tw** [adarsh-a-tw/Movies#1]
<img width="1792" alt="Screenshot 2022-09-15 at 2 22 37 AM" src="https://user-images.githubusercontent.com/65023866/190262743-8b02ac61-6131-4b1d-a915-5e3f677cb8d0.png">

**Comment by adarsh-a-tw** [comment]
@shebin-tw  Can you please set the API URL as an environment variable in the scheme in Xcode. I thought it is not a good practice to push environment vars to git

**Comment by shebin-tw** [comment]
ok fine.
Hope you are talking about the below environment variable section. 
<img width="929" alt="Screenshot 2022-09-15 at 3 25 44 PM" src="https://user-images.githubusercontent.com/65023866/190376700-cc3b8951-906f-47fc-a9ed-71d4390df2de.png">

If so, these values may not come in release build, there are other ways to configure base urls based on environment (DEV,QA,PROD),  Among that, one of the way is under build settings -> User-defined key value pairs

**Comment by adarsh-a-tw** [comment]
Oh great ! I didn't know about that. Thanks for letting me know.
