### ISSUE TITLE
Suggestion: Can we split the function further?

### ISSUE THREAD

**Issue by shebin-tw** [adarsh-a-tw/Movies#3]
Suggestion: Can we split the function further?
A bit complicated to understand at first look.
https://github.com/adarsh-a-tw/Movies/blob/d85364b1179512ef1d029f233a1ceed97cb6ada1/Movies/ViewModels/MovieViewModel.swift#L26

**Comment by adarsh-a-tw** [comment]
Refactored as per suggestion
