### ISSUE TITLE
Suggestion: good to create a movieTileViewModel and move image name & string to viewModel 

### ISSUE THREAD

**Issue by shebin-tw** [adarsh-a-tw/Movies#8]
Suggestion: good to create a movieTileViewModel and move image name & string to viewModel 

https://github.com/adarsh-a-tw/Movies/blob/c3af916d7a9e5a07cb04002b99b850e8f290e084/Movies/Views/MovieTileView.swift#L25

https://github.com/adarsh-a-tw/Movies/blob/c3af916d7a9e5a07cb04002b99b850e8f290e084/Movies/Views/MovieTileView.swift#L26

**Comment by adarsh-a-tw** [comment]
@shebin-tw  I have created View models for each View. I referred  [this medium article](https://azamsharp.medium.com/mvvm-in-swiftui-8a2e9cc2964a) for implementing this. Can you please validate this approach ?

**Comment by shebin-tw** [comment]
@adarsh-a-tw  Looks good to me
